version: '3'
services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    ports:
      - 13306:3306
